# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 09:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='nota',
        ),
        migrations.AddField(
            model_name='nota',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 9, 9, 50, 613298, tzinfo=utc)),
        ),
    ]
