# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0002_auto_20170228_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
